import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "./components/layout/Sidebar";
import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen flex bg-[#1a1a1a] text-gray-200`}
      >
        {/* Sidebar fijo solo en desktop */}
        <div className="hidden md:flex">
          <SideBar />
        </div>

        {/* Contenedor principal: header, main y footer */}
        <div className="flex-1 flex flex-col min-h-screen">
          {/* Header siempre visible */}
          <Header />

          {/* Contenido principal con padding para evitar que quede debajo del header */}
          <main className="flex-1 p-6 overflow-auto">{children}</main>

          {/* Footer */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
